import sys
import logging
import requests
import pandas as pd
from pathlib import Path

# Stub train-serve parity script
# In production, this would:
# 1. Sample N rows from ml/data/out/bookings.parquet
# 2. Send identical payloads to the POST /api/bookings endpoint
# 3. Intercept the feature vector generated by Node (via a test endpoint or DB query)
# 4. Compare Node's feature vector vs Python's generate.py features
# 5. Fail if np.allclose is False

logging.basicConfig(level=logging.INFO)

def run_parity_check():
    logging.info("Starting train-serve parity check...")
    data_path = Path(__file__).parent.parent / "data" / "out" / "bookings.parquet"
    if not data_path.exists():
        logging.error("No training data found. Run generate.py first.")
        sys.exit(1)
        
    df = pd.read_parquet(data_path)
    sample = df.sample(10, random_state=42)
    logging.info(f"Loaded {len(sample)} sample records.")
    
    # Example logic (mocked)
    parity_success = True
    for _, row in sample.iterrows():
        # TODO: send to Node, get features, compare
        pass
        
    if parity_success:
        logging.info("SUCCESS: Train-serve parity verified! Features match.")
    else:
        logging.error("FAILED: Feature mismatch detected between Node (Serve) and Python (Train).")
        sys.exit(1)

if __name__ == "__main__":
    run_parity_check()
