const RULES = [
  // ── BEHAVIORAL RULES ──
  {
    code: 'WEIGHT_3X_NORMAL',
    name: 'Shipment weight significantly above average',
    category: 'BEHAVIOR',
    risk_points: 15,
    evaluate: (f) => f.behavioral.weight_ratio_to_avg >= 3 && f.behavioral.total_historical_shipments > 5,
    description: (f) => `Shipment weight is ${f.behavioral.weight_ratio_to_avg}× the shipper's historical average`,
  },
  {
    code: 'WEIGHT_EXCEEDS_MAX',
    name: 'Weight exceeds historical maximum',
    category: 'BEHAVIOR',
    risk_points: 10,
    evaluate: (f) => f.behavioral.weight_exceeds_max,
    description: () => 'Shipment weight exceeds the shipper\'s historical maximum',
  },
  {
    code: 'EXTREME_WEIGHT',
    name: 'Extremely high absolute weight',
    category: 'BEHAVIOR',
    risk_points: 15,
    evaluate: (f) => f.behavioral.weight_z_score > 5, // A Z-score > 5 or just extreme value
    description: () => 'Shipment weight is an extreme statistical outlier',
  },
  {
    code: 'HIGH_RISK_ROUTE',
    name: 'High risk corridor routing',
    category: 'BEHAVIOR',
    risk_points: 25,
    evaluate: (f) => f.behavioral.is_new_origin && f.behavioral.is_new_destination,
    description: () => 'Route involves an entirely new origin and destination corridor',
  },
  {
    code: 'NEW_DESTINATION',
    name: 'Destination is new for this shipper',
    category: 'BEHAVIOR',
    risk_points: 8,
    evaluate: (f) => f.behavioral.is_new_destination && f.behavioral.total_historical_shipments > 5,
    description: () => 'Destination is unusual for this shipper based on historical patterns',
  },
  {
    code: 'NEW_ORIGIN',
    name: 'Origin is new for this shipper',
    category: 'BEHAVIOR',
    risk_points: 6,
    evaluate: (f) => f.behavioral.is_new_origin && f.behavioral.total_historical_shipments > 5,
    description: () => 'Origin has not been used by this shipper before',
  },
  {
    code: 'UNUSUAL_SERVICE_TYPE',
    name: 'Unusual service type selection',
    category: 'BEHAVIOR',
    risk_points: 5,
    evaluate: (f) => f.behavioral.is_unusual_service,
    description: () => 'Service type is unusual for this shipper\'s typical booking pattern',
  },
  {
    code: 'UNUSUAL_BOOKING_HOUR',
    name: 'Booking at unusual hour',
    category: 'BEHAVIOR',
    risk_points: 5,
    evaluate: (f) => f.behavioral.is_unusual_hour,
    description: (f) => `Booking at hour ${f.behavioral.booking_hour} UTC is outside the shipper's normal business hours`,
  },
  {
    code: 'LOW_HISTORY_SHIPPER',
    name: 'Shipper with limited history',
    category: 'BEHAVIOR',
    risk_points: 8,
    evaluate: (f) => f.behavioral.is_low_history,
    description: (f) => `Shipper has only ${f.behavioral.total_historical_shipments} historical shipments — limited behavioral baseline`,
  },

  // ── IDENTITY RULES ──
  {
    code: 'NEW_DEVICE_FOR_ACCOUNT',
    name: 'New device not associated with this account',
    category: 'IDENTITY',
    risk_points: 12,
    evaluate: (f) => f.identity.is_new_device,
    description: () => 'Booking device has not been previously associated with this account',
  },
  {
    code: 'NEW_PAYMENT_FOR_ACCOUNT',
    name: 'New payment method for this account',
    category: 'IDENTITY',
    risk_points: 8,
    evaluate: (f) => f.identity.is_new_payment_for_account,
    description: () => 'Payment method has not been previously used by this account',
  },
  {
    code: 'RECENT_PASSWORD_CHANGE',
    name: 'Password changed within 72 hours',
    category: 'IDENTITY',
    risk_points: 10,
    evaluate: (f) => f.identity.password_changed_recently,
    description: () => 'Account password was changed within the last 72 hours — potential account takeover',
  },
  {
    code: 'RECENT_PROFILE_UPDATE',
    name: 'Profile updated within 48 hours',
    category: 'IDENTITY',
    risk_points: 6,
    evaluate: (f) => f.identity.profile_updated_recently,
    description: () => 'Account profile was updated within the last 48 hours',
  },
  {
    code: 'ACCOUNT_SUSPENDED',
    name: 'Account is suspended',
    category: 'IDENTITY',
    risk_points: 30,
    evaluate: (f) => f.identity.is_suspended,
    description: () => 'Shipping from a suspended account',
  },
  {
    code: 'ACCOUNT_UNDER_INVESTIGATION',
    name: 'Account is under investigation',
    category: 'IDENTITY',
    risk_points: 20,
    evaluate: (f) => f.identity.is_under_investigation,
    description: () => 'Account is currently under fraud investigation',
  },
  {
    code: 'NEW_ACCOUNT',
    name: 'Account is less than 30 days old',
    category: 'IDENTITY',
    risk_points: 8,
    evaluate: (f) => f.identity.is_new_account,
    description: (f) => `Account is only ${f.identity.account_age_days} days old`,
  },
  {
    code: 'UNVERIFIED_ACCOUNT',
    name: 'Account is not verified',
    category: 'IDENTITY',
    risk_points: 10,
    evaluate: (f) => !f.identity.is_verified,
    description: () => 'Account has not completed identity verification',
  },
  {
    code: 'PRIOR_FRAUD_HISTORY',
    name: 'Previous fraud cases on account',
    category: 'IDENTITY',
    risk_points: 25,
    evaluate: (f) => f.identity.previous_fraud_cases > 0,
    description: (f) => `Account has ${f.identity.previous_fraud_cases} previous confirmed fraud case(s)`,
  },

  // ── PAYMENT RULES ──
  {
    code: 'NEW_PAYMENT_METHOD',
    name: 'Brand new payment method',
    category: 'PAYMENT',
    risk_points: 10,
    evaluate: (f) => f.payment.is_new_payment_method,
    description: () => 'Payment method is newly registered with no transaction history',
  },
  {
    code: 'CARDHOLDER_MISMATCH',
    name: 'Cardholder name does not match account',
    category: 'PAYMENT',
    risk_points: 8,
    evaluate: (f) => f.payment.payment_found && !f.payment.cardholder_match,
    description: () => 'Cardholder name does not match the registered account holder',
  },
  {
    code: 'BILLING_SHIPPING_MISMATCH',
    name: 'Billing and shipping address mismatch',
    category: 'PAYMENT',
    risk_points: 6,
    evaluate: (f) => f.payment.payment_found && !f.payment.billing_shipping_match,
    description: () => 'Billing address does not match the shipping origin',
  },
  {
    code: 'PAYMENT_FRAUD_HISTORY',
    name: 'Payment method has fraud history',
    category: 'PAYMENT',
    risk_points: 25,
    evaluate: (f) => f.payment.previous_fraud_count > 0,
    description: (f) => `Payment method has been involved in ${f.payment.previous_fraud_count} previous fraud case(s)`,
  },
  {
    code: 'FOREIGN_CARD',
    name: 'Foreign-issued payment card',
    category: 'PAYMENT',
    risk_points: 5,
    evaluate: (f) => f.payment.foreign_card,
    description: () => 'Payment card was issued outside of India',
  },

  // ── DEVICE / IP RULES ──
  {
    code: 'VPN_DETECTED',
    name: 'VPN connection detected',
    category: 'DEVICE',
    risk_points: 8,
    evaluate: (f) => f.device.vpn_detected,
    description: () => 'Booking was made through a VPN connection',
  },
  {
    code: 'PROXY_DETECTED',
    name: 'Proxy connection detected',
    category: 'DEVICE',
    risk_points: 10,
    evaluate: (f) => f.device.proxy_detected,
    description: () => 'Booking was made through a proxy server',
  },
  {
    code: 'DEVICE_BLACKLISTED',
    name: 'Device is blacklisted',
    category: 'DEVICE',
    risk_points: 30,
    evaluate: (f) => f.device.device_blacklisted,
    description: () => 'Booking device is on the blacklist',
  },
  {
    code: 'IP_BLACKLISTED',
    name: 'IP address is blacklisted',
    category: 'DEVICE',
    risk_points: 25,
    evaluate: (f) => f.device.ip_blacklisted,
    description: () => 'IP address is on the blacklist',
  },
  {
    code: 'DEVICE_LINKED_TO_FRAUD',
    name: 'Device linked to previously flagged accounts',
    category: 'DEVICE',
    risk_points: 15,
    evaluate: (f) => f.device.device_linked_to_fraud,
    description: (f) => `Device is linked to ${f.device.linked_fraud_account_count} previously flagged account(s)`,
  },
  {
    code: 'HIGH_DEVICE_SHARING',
    name: 'Device linked to many accounts',
    category: 'DEVICE',
    risk_points: 10,
    evaluate: (f) => f.device.accounts_linked >= 5,
    description: (f) => `Device is linked to ${f.device.accounts_linked} different accounts`,
  },
  {
    code: 'SUSPICIOUS_IP_REPUTATION',
    name: 'IP has suspicious reputation',
    category: 'DEVICE',
    risk_points: 8,
    evaluate: (f) => ['SUSPICIOUS', 'HIGH_RISK'].includes(f.device.ip_reputation),
    description: (f) => `IP reputation is ${f.device.ip_reputation}`,
  },

  // ── ADDRESS RULES ──
  {
    code: 'LOW_ADDRESS_CONFIDENCE',
    name: 'Low destination address confidence',
    category: 'ADDRESS',
    risk_points: 8,
    evaluate: (f) => f.address.confidence_score < 0.5,
    description: (f) => `Destination address confidence is only ${Math.round(f.address.confidence_score * 100)}%`,
  },
  {
    code: 'HIGH_RISK_ADDRESS',
    name: 'Destination is in a high-risk area',
    category: 'ADDRESS',
    risk_points: 10,
    evaluate: (f) => f.address.risk_tier === 'HIGH',
    description: () => 'Destination is classified as a high-risk delivery area',
  },
  {
    code: 'INVALID_ADDRESS',
    name: 'Address could not be validated',
    category: 'ADDRESS',
    risk_points: 12,
    evaluate: (f) => !f.address.address_valid,
    description: () => 'Destination address could not be validated',
  },

  // ── VELOCITY RULES ──
  {
    code: 'LATE_NIGHT_BOOKING',
    name: 'Late night booking',
    category: 'VELOCITY',
    risk_points: 5,
    evaluate: (f) => f.velocity.is_late_night,
    description: (f) => `Booking made at ${f.velocity.booking_hour}:00 UTC (late night)`,
  },
  {
    code: 'VOLUME_SPIKE',
    name: 'Volume spike detected',
    category: 'VELOCITY',
    risk_points: 12,
    evaluate: (f) => f.velocity.volume_spike_detected,
    description: () => 'Shipping volume significantly exceeds the shipper\'s normal daily rate',
  },

  // ── MITIGATING RULES (negative points) ──
  {
    code: 'ESTABLISHED_ACCOUNT',
    name: 'Well-established account with clean history',
    category: 'IDENTITY',
    risk_points: -10,
    evaluate: (f) =>
      f.identity.account_age_days > 365 &&
      f.identity.previous_fraud_cases === 0 &&
      f.behavioral.total_historical_shipments > 100,
    description: (f) => `Well-established account (${f.identity.account_age_days} days old, ${f.behavioral.total_historical_shipments} shipments, zero fraud)`,
  },
  {
    code: 'KNOWN_DEVICE_AND_PAYMENT',
    name: 'Using known device and known payment',
    category: 'IDENTITY',
    risk_points: -8,
    evaluate: (f) => !f.identity.is_new_device && !f.identity.is_new_payment_for_account,
    description: () => 'Booking uses a previously known device and payment method for this account',
  },
  {
    code: 'HIGH_ADDRESS_CONFIDENCE',
    name: 'High confidence destination address',
    category: 'ADDRESS',
    risk_points: -5,
    evaluate: (f) => f.address.confidence_score >= 0.90,
    description: (f) => `Destination has ${Math.round(f.address.confidence_score * 100)}% confidence with strong delivery history`,
  },
];

module.exports = { RULES };
